### ISSUE TITLE
The LM master alarm sound does not turn off

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#491] opened 2019-06-16 01:55 UTC
I've been training apollo 11. I started activating LM today. During the activation of the LM, when I closed the Master Alarm cb, the alarm sound started  as usually. But then I could not turn it off by pressing the Master alarm button. The only way to work , is to save, and  reload, and then it works fine. Just to report! :). I'm with the version NASSP-V8.0-Alpha-Orbiter2016-1445.

https://puu.sh/DGyEe/dac106f67a.png

https://puu.sh/DGyEs/350fc87055.png

Best regards

**Comment by indy91** [comment] 2019-06-16 16:43
Probably caused by https://github.com/dseagrav/NASSP/commit/abbc3d3774ee8d2ba241be17db5cb5f8859ea32b, which had some unsafe code, also makes the ECS light flicker. I already have the fix locally, will push it soon. Then you can check if that was the issue.

**Comment by indy91** [comment] 2019-06-16 18:35
Should be fixed by https://github.com/dseagrav/NASSP/commit/81156ef84172d68d316d87cb0d74cbc6d22c34f1

**Comment by RL77** [comment] 2019-06-16 20:59
Ok Thanks, going to update, go back and test it!

**Comment by RL77** [comment] 2019-06-17 21:27
Hello,

Seems okay now! I'm going to start the  undocking of the LM to see if it's okay from now on. Since January when I finally managed to finish Apollo 11, I have always been flying this mission. This is my 8th apollo11, and I will continue until is possible to fly apollo12 and so on. So I'll report if I find a bug. Since you are now always updating NASSP (which is great !!) it will be easier to detect something while training apollo 11.

Thanks !

**Comment by jalexb88** [comment] 2019-06-18 00:32
Apollo 12 and later should be already possible to fly already, but of course no MCC yet so you will need to know how to use the RTCC MFD for all uplinks and maneuver pads.

**Comment by RL77** [comment] 2019-06-18 19:06
Yes I know, I tried but I was not very successful.. Is there already a new APOLLO RTCC MFD  manual that can help us?

**Closed** 2019-06-22 17:40 UTC
