### ISSUE TITLE
Need CSM ECS connection to LM Cabin to prevent CO2 buildup before LM ECS is activated

### ISSUE THREAD

**Issue by RL77** [dseagrav/NASSP#621] opened 2021-06-01 01:50 UTC
Hello,

When I start activating ECS on the LEM on Apollo 11, at a certain point when I move the SUIT ISOL button to “SUIT FlOW” (CDR to LM ECS), the partial pressure of CO2 starts to rise to about 15. Then it starts descending until close to 10. When the time comes to close the LEM and CSM hatch, CO2 starts to rise again until + - 15, then goes down again, but in the meantime the crew dies in GET + - 97h20min. What I do, is not to change SUIT ISOL to “SUIT FlOW”, so that the partial pressure of CO2 does not rise. If I don't do this, the LEM crew will die. I send a video so that you can see better, and my scenario. I am now using version 1673. I had already noticed this behavior of CO2 in the mission I did previously (with version 1641), but curiously the crew did not die.

Video:

https://we.tl/t-xLOG40shpb 

scenario:

https://we.tl/t-i9CcAgpi5M

Thanks

**Comment by rcflyinghokie** [comment] 2021-06-01 18:47
So it looks like the issue is the CO2 in the cabin built up to very high levels during your other LM INGRESS periods.  Because of this, when you turned on the suit fan, all of that CO2 is brought into the suit circuit (and therefore the CO2 sensor) causing the gauge to climb high.

This is an issue I have looked at resolving as in the spacecraft during shirt sleeve LM ingress periods they would bring a hose from the CSM ECS to circulate air in the LM.  

In your case, put the crew back in the CSM and run the ECS with both suit ISOL valves in SUIT FLOW, a PREG in CABIN, and SUIT GAS DIVERTER in CABIN until the CO2 comes down then add the crew back and configure per the checklist.

Additionally, I have renamed this issue to be more specific and will keep it open as it is important to address.

**Comment by RL77** [comment] 2021-06-01 20:52
Hello,

Thank you very much  for your explanations on the subject and help. Going to try that soon!

**Comment by RL77** [comment] 2021-06-03 20:51
Hello,
I found an alternative way to get around this situation without having to take the crew out of the LM. After the CO2 starts to rise, when it is too high, we simply put the PRESS REG A to Direct O2 for a while (or PRESS REG B ), and then back to EGRESS. We can do this from time to time as we do the checklist. Finally, after we finish the CABIN REGULATOR CHECK on the checklist, the CO2 drops to zero, and remains at acceptable values.

**Comment by rcflyinghokie** [comment] 2021-06-04 11:20
> Hello,
> I found an alternative way to get around this situation without having to take the crew out of the LM. After the CO2 starts to rise, when it is too high, we simply put the PRESS REG A to Direct O2 for a while (or PRESS REG B ), and then back to EGRESS. We can do this from time to time as we do the checklist. Finally, after we finish the CABIN REGULATOR CHECK on the checklist, the CO2 drops to zero, and remains at acceptable values.

While this may be a work around, it is not very realistic in terms of how the mission should be carried out.  The hose I am implementing is actually what was used during the missions to keep this from happening. By opening DIRECT O2, you are just pumping in fresh O2 without using the the cabin or egress regulators and essentially over pressurize the suit circuit, which then relieves into the cabin, and if that gets too high, vents into space via the LM or CSM pressure relief valves. Additionally, you are not removing CO2 any faster this way, you just reduce the partial pressure of CO2 by increasing the O2 pressure in the suit loop not removing it from the cabin, where the problem lies.

**Comment by RL77** [comment] 2021-06-04 20:06
Hi,

Well I know it's just a way to work around, and I figured it wasn't realistic. I also know that it was probably only reducing the partial pressure of CO2 by increasing the partial pressure of O2, but it  kept the crew from dying. Anyway I'm already going to DOI , see if I still land today :).  Thanks for the explanation on the  subject again!

**Comment by RL77** [comment] 2021-06-05 19:48
Hi,
I know this is out of this subject, but I just wanted to leave a video of my second manual landing with the LM 3D cockpit I did yesterday! :) 

https://we.tl/t-eGqCKlTNtq

**Comment by rcflyinghokie** [comment] 2021-07-12 19:34
#622 Added CSM O2 hose for use to mitigate prolonged CO2 buildup.  Procedures will be added to checklist MFD at a later date.

To use the O2 Hose, you must be docked and in a shirtsleeve configuration.  Connect the hose with PAMFD ECS page.  Set Suit flow valves to suit full flow.

**Comment by RL77** [comment] 2021-07-13 15:22
Hello,

Thank you very much for the information! I'm going to start a new Apollo 11 mission soon! Just a question, I should only use the hose for the first time  when I open the LM to set it up for descent right? or do I start using it as soon as I enter the LM during TranslunarCoast?

Thanks

**Comment by RL77** [comment] 2021-08-23 22:31
Hello,

I started a new mission last August 6th, I couldn't start any earlier. The hose worked perfectly, I connected it the 1st and 2nd time we entered the LM. When it came time to enter the 3rd time to prepare the LM for descent, the CO2 level rised to a maximum of 5. There was no problem with the CO2. I finished the mission with update 1696, everything went well, no bugs.

**Closed as completed** 2021-08-30 23:16 UTC
